server.port: 8080

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

spring:
  mvc:
    problemdetails:
      enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}