version: "3.1"
services:
  user:
    working_dir: /home/app
    container_name: microservice-client-devsu
    image: amazoncorretto:17-alpine
    deploy:
      resources:
        limits:
          memory: 512M
    command: >
      sh -c "chmod 777 ./gradlew && ./gradlew clean && ./gradlew bootRun"
    volumes:
      - ./:/home/app
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_DRIVER=${DATASOURCE_DRIVER}
      - DATASOURCE_URL=${DATASOURCE_URL}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - appnet
  rabbitmq:
    container_name: devsu-rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - appnet
  postgres:
    container_name: devsu-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    networks:
      - appnet
networks:
  appnet: